src/main/java/io/gravitee/policy/oauth2/Oauth2Policy.java

fix(oauth2): Send a service unavailable status code if oauth2 server is not accessible

---

README.adoc
pom.xml
src/main/java/io/gravitee/policy/oauth2/Oauth2Policy.java
src/main/java/io/gravitee/policy/oauth2/configuration/OAuth2PolicyConfiguration.java
src/main/resources/schemas/urn:jsonschema:io:gravitee:policy:oauth2:configuration:OAuth2PolicyConfiguration.json
src/test/java/io/gravitee/policy/oauth2/OAuth2PolicyTest.java

feat(oauth2): Add OAuth2 attributes in execution context

---

pom.xml
src/main/java/io/gravitee/policy/oauth2/Oauth2Policy.java
src/test/java/io/gravitee/policy/oauth2/OAuth2PolicyTest.java

feat(oauth2): Use the OAuth2 resource provider API

---

README.adoc

doc: Add sample to extract token introspection payload

---

pom.xml
src/main/java/io/gravitee/policy/oauth2/Oauth2Policy.java
src/test/java/io/gravitee/policy/oauth2/OAuth2PolicyTest.java
src/test/resources/io/gravitee/policy/oauth2/oauth2-response06.json

Closes gravitee-io/issues#1001

feat(oauth2): Add scope delimiter configuration

---

pom.xml
src/test/java/io/gravitee/policy/oauth2/OAuth2PolicyTest.java

chore: Java 11 support

---

pom.xml
src/main/java/io/gravitee/policy/oauth2/Oauth2Policy.java
src/test/java/io/gravitee/policy/oauth2/OAuth2PolicyTest.java

This closes gravitee-io/issues#1948

feat: Audit on API user from JWT

---

pom.xml
src/main/java/io/gravitee/policy/oauth2/Oauth2Policy.java
src/test/java/io/gravitee/policy/oauth2/OAuth2PolicyTest.java

feat(role): Inject scopes as role in execution context

---

README.adoc
pom.xml
src/main/java/io/gravitee/policy/oauth2/Oauth2Policy.java
src/test/java/io/gravitee/policy/oauth2/OAuth2PolicyTest.java

closes gravitee-io/issues#2208

Feat: Add response template keys

---

src/main/java/io/gravitee/policy/oauth2/Oauth2Policy.java
src/test/java/io/gravitee/policy/oauth2/OAuth2PolicyTest.java

https://github.com/gravitee-io/issues/issues/2629

Support EL in resource name

---

src/main/java/io/gravitee/policy/oauth2/Oauth2Policy.java

Closes gravitee-io/issues#3264

fix: User is not logged anymore

---

src/main/resources/schemas/schema-form.json

feat: add autocomplete on resource field of form

---

pom.xml
src/main/java/io/gravitee/policy/oauth2/Oauth2Policy.java
src/test/java/io/gravitee/policy/oauth2/OAuth2PolicyTest.java

refactor(cache): use new CacheResource

---

pom.xml
src/main/java/io/gravitee/policy/oauth2/Oauth2Policy.java

feat(management): platform policies

---

pom.xml
src/main/java/io/gravitee/policy/oauth2/Oauth2Policy.java
src/test/java/io/gravitee/policy/oauth2/OAuth2PolicyTest.java

Closes gravitee-io/issues#6772

feat(headers): Internal rework and introduce HTTP Headers API

---

pom.xml
src/main/java/io/gravitee/policy/oauth2/Oauth2Policy.java
src/main/java/io/gravitee/policy/oauth2/utils/TokenExtractor.java

**Issue**
https://github.com/gravitee-io/issues/issues/8009
Update policy to handle new message execution context
---
**Gravitee.io Automatic Deployment**
🚀 A prerelease version of this package has been published on Gravitee's private artifactory, you can:
- use it directly by updating your project with version: `1.21.0-8238-entrypoint-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-oauth2/1.21.0-8238-entrypoint-SNAPSHOT/gravitee-policy-oauth2-1.21.0-8238-entrypoint-SNAPSHOT.zip)

update security policy to be compatible with async reactor

---

pom.xml
src/main/java/io/gravitee/policy/oauth2/Oauth2Policy.java
src/main/java/io/gravitee/policy/oauth2/introspection/TokenIntrospectionCache.java
src/main/java/io/gravitee/policy/oauth2/introspection/TokenIntrospectionResult.java
src/test/java/io/gravitee/policy/oauth2/DummyOAuth2Resource.java
src/test/java/io/gravitee/policy/oauth2/Oauth2PolicyIntegrationTest.java
src/test/java/io/gravitee/policy/oauth2/Oauth2PolicyTest.java
src/test/java/io/gravitee/policy/oauth2/Oauth2PolicyV3CompatibilityIntegrationTest.java
src/test/java/io/gravitee/policy/oauth2/introspection/TokenIntrospectionCacheTest.java
src/test/java/io/gravitee/policy/oauth2/introspection/TokenIntrospectionResultTest.java
src/test/java/io/gravitee/policy/v3/oauth2/Oauth2PolicyV3IntegrationTest.java
src/test/resources/apis/oauth2.json
src/test/resources/io/gravitee/policy/oauth2/oauth2-response09.json

**Issue**
https://github.com/gravitee-io/issues/issues/7991
---
**Gravitee.io Automatic Deployment**
🚀 A prerelease version of this package has been published on Gravitee's private artifactory, you can:
- use it directly by updating your project with version: `1.22.0-feat-jupiterPlans-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-oauth2/1.22.0-feat-jupiterPlans-SNAPSHOT/gravitee-policy-oauth2-1.22.0-feat-jupiterPlans-SNAPSHOT.zip)

feat: migrate to the new version of Jupiter's SecurityPolicy

---

src/main/resources/schemas/schema-form.json

**Issue**
https://gravitee.atlassian.net/browse/APIM-2088
Improve special resource type ui component to make it generic
**Additional context**
---
**Gravitee.io Automatic Deployment**
🚀 A prerelease version of this package has been published on Gravitee's private artifactory, you can:
- use it directly by updating your project with version: `2.3.0-json-schema-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-oauth2/2.3.0-json-schema-SNAPSHOT/gravitee-policy-oauth2-2.3.0-json-schema-SNAPSHOT.zip)

feat: improve special resource type ui component to make it generic

---

.circleci/config.yml

**Issue**
NA
Bump Gravitee orb to allow CI to run for PR from forks

Bump Gravitee orb to allow CI to run for PR from forks

---

README.adoc

**Issue**
https://gravitee.atlassian.net/browse/APIM-6475
Update documentation to match status quo.
**Additional context**
---
**Gravitee.io Automatic Deployment**
🚀 A prerelease version of this package has been published on Gravitee's private artifactory, you can:
- use it directly by updating your project with version: `3.0.5-apim-6475-update-status-code-documentation-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-oauth2/3.0.5-apim-6475-update-status-code-documentation-SNAPSHOT/gravitee-policy-oauth2-3.0.5-apim-6475-update-status-code-documentation-SNAPSHOT.zip)

fix: Update status code in documentation

---

.circleci/config.yml
.github/pull_request_template.md
.github/renovate.json
CHANGELOG.md
README.adoc
pom.xml
src/main/java/io/gravitee/policy/oauth2/Oauth2Policy.java
src/main/java/io/gravitee/policy/oauth2/introspection/TokenIntrospectionResult.java
src/main/java/io/gravitee/policy/oauth2/utils/TokenExtractor.java
src/test/java/io/gravitee/policy/oauth2/Oauth2PolicyTest.java

Merge 'alpha' into master
